version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app/backend
    ports:
      - "3001:3001"
    command: npm start

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app/frontend
    ports:
      - "3000:3000"
    command: npm start
